//// CART
export const CART_LIST_ADD = "CART_LIST_ADD";
export const CART_LIST_DELETE = "CART_LIST_DELETE";
export const CART_LIST_UPDATE = "CART_LIST_UPDATE";
export const CART_LIST_UPDATE_CLICK = "CART_LIST_UPDATE_CLICK";
export const CART_LIST_DELETE_ALL_CART = "CART_LIST_DELETE_ALL_CART";

//// LOGIN
export const LOGIN_USER = "LOGIN_USER";
export const LOGOUT_USER = "LOGOUT_USER";

///PAYMENT

export const PAYMENT_CUSTODY = "PAYMENT_CUSTODY";
